version: '2'
services:
  bootcamp-app:
    image: bootcamp
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bootcamp-postgresql:5432/bootcamp
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://bootcamp-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://bootcamp-elasticsearch:9200
    ports:
      - 8080:8080
  bootcamp-postgresql:
    extends:
      file: postgresql.yml
      service: bootcamp-postgresql
  bootcamp-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: bootcamp-elasticsearch
